// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ZQ_pS7_NDFgcmljGeLSy0dt9YvkKE24',
    appId: '1:687279755567:web:6b94a86af0add08cc311da',
    messagingSenderId: '687279755567',
    projectId: 'chatly-3ca5c',
    authDomain: 'chatly-3ca5c.firebaseapp.com',
    storageBucket: 'chatly-3ca5c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALJ3bDsiF0K7VvF1Qd7xcPn76X0a5a0OA',
    appId: '1:687279755567:android:de0c628a8fbe7ae1c311da',
    messagingSenderId: '687279755567',
    projectId: 'chatly-3ca5c',
    storageBucket: 'chatly-3ca5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6OhLLdddVw_zLtcv3SCfEEpHJIu8cAus',
    appId: '1:687279755567:ios:e26f5a7c202a72b6c311da',
    messagingSenderId: '687279755567',
    projectId: 'chatly-3ca5c',
    storageBucket: 'chatly-3ca5c.firebasestorage.app',
    androidClientId:
        '687279755567-o4sptrns56ad094l53ksd9bu3cqlpfov.apps.googleusercontent.com',
    iosClientId:
        '687279755567-f7roreqsrml36ofmkm57t7u7f2tnaeee.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatlyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6OhLLdddVw_zLtcv3SCfEEpHJIu8cAus',
    appId: '1:687279755567:ios:e26f5a7c202a72b6c311da',
    messagingSenderId: '687279755567',
    projectId: 'chatly-3ca5c',
    storageBucket: 'chatly-3ca5c.firebasestorage.app',
    androidClientId:
        '687279755567-o4sptrns56ad094l53ksd9bu3cqlpfov.apps.googleusercontent.com',
    iosClientId:
        '687279755567-f7roreqsrml36ofmkm57t7u7f2tnaeee.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatlyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ZQ_pS7_NDFgcmljGeLSy0dt9YvkKE24',
    appId: '1:687279755567:web:b336a29db1b46991c311da',
    messagingSenderId: '687279755567',
    projectId: 'chatly-3ca5c',
    authDomain: 'chatly-3ca5c.firebaseapp.com',
    storageBucket: 'chatly-3ca5c.firebasestorage.app',
  );
}
