import 'screens/settings/privacy_settings_screen.dart';
import 'services/app_lifecycle_service.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

// Firebase config (generated by flutterfire configure)
import 'firebase_options.dart';

// App routes & screens
import 'app_routes.dart';

// Services
import 'services/notification_service.dart';
import 'services/auth_service.dart';

// Providers
import 'providers/settings_provider.dart';

// Themes
import 'core/theme/app_theme.dart';

// Screens
import 'screens/splash_screen.dart';
import 'screens/onboarding/welcome_screen.dart';
import 'screens/onboarding/onboarding_screen.dart';
import 'screens/auth/login_screen.dart';
import 'screens/auth/signup_screen.dart';
import 'screens/auth/forgot_password_screen.dart';
import 'screens/home/home_screen.dart';
import 'screens/home/chat_screen.dart';
import 'screens/home/group_chat_screen.dart';
import 'screens/home/create_group_screen.dart';
import 'screens/home/join_group_screen.dart';
import 'screens/home/group_settings_screen.dart';
import 'screens/home/mood_tracking_screen.dart';
import 'screens/home/qr_code_screen.dart';
import 'screens/home/qr_scanner_screen.dart';
import 'screens/home/unblock_requests_screen.dart';
import 'screens/profile/profile_screen.dart';
import 'screens/profile/edit_profile_screen.dart';
import 'screens/settings/settings_screen.dart';

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print("Handling a background message: ${message.messageId}");
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase with correct options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  // Request Notification Permission (iOS required, Android recommended)
  final messaging = FirebaseMessaging.instance;
  await messaging.requestPermission(
    alert: true,
    badge: true,
    sound: true,
  );

  // Handle Notifications in Flutter Foreground
  FirebaseMessaging.onMessage.listen((RemoteMessage message) {
    print("Got a message in foreground: ${message.notification?.title}");
  });

  // App opened by tapping notification
  FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
    print("Opened app from notification: ${message.data}");
    // Navigate to the chat screen
  });

  // ✅ Initialize Notification Service
  final notificationService = NotificationService();
  await notificationService.initialize();

  // ✅ Update FCM Token if user is logged in
  final fcmToken = await notificationService.getFCMToken();
  if (fcmToken != null && FirebaseAuth.instance.currentUser != null) {
    final authService = AuthService();
    await authService.updateFcmToken(
        FirebaseAuth.instance.currentUser!.uid, fcmToken);
  }

  runApp(ProviderScope(child: const ChatlyApp()));
}

class ChatlyApp extends ConsumerStatefulWidget {
  const ChatlyApp({super.key});

  @override
  ConsumerState<ChatlyApp> createState() => _ChatlyAppState();
}

class _ChatlyAppState extends ConsumerState<ChatlyApp> {
  @override
  void initState() {
    super.initState();
    ref.read(appLifecycleServiceProvider).init();
  }

  @override
  Widget build(BuildContext context) {
    final settings = ref.watch(settingsProvider);
    final selectedThemeMode = resolveThemeMode(settings.themeMode);

    return MaterialApp(
      title: 'Chatly',
      debugShowCheckedModeBanner: false,
      theme: getLightTheme(settings.themePreset),
      darkTheme: getDarkTheme(settings.themePreset),
      themeMode: selectedThemeMode,
      initialRoute: AppRoutes.splash,
      routes: {
        AppRoutes.splash: (_) => const SplashScreen(),
        AppRoutes.welcome: (_) => const WelcomeScreen(),
        AppRoutes.onboarding: (_) => const OnboardingScreen(),
        AppRoutes.login: (_) => const LoginScreen(),
        AppRoutes.signup: (_) => const SignupScreen(),
        AppRoutes.forgotPassword: (_) => const ForgotPasswordScreen(),
        AppRoutes.home: (_) => const HomeScreen(),
        AppRoutes.chat: (context) {
          final args = ModalRoute.of(context)?.settings.arguments
              as Map<String, dynamic>?;
          return ChatScreen(
            chatId: args?['chatId']?.toString() ?? '',
            receiverId: args?['receiverId']?.toString() ?? '',
            currentUserId: args?['currentUserId']?.toString() ?? '',
          );
        },
        AppRoutes.groupChat: (context) {
          final args = ModalRoute.of(context)?.settings.arguments
              as Map<String, dynamic>?;
          return GroupChatScreen(
            groupId: args?['groupId']?.toString() ?? '',
            currentUserId: args?['currentUserId']?.toString() ?? '',
          );
        },
        AppRoutes.createGroup: (context) => const CreateGroupScreen(),
        AppRoutes.joinGroup: (context) => const JoinGroupScreen(),
        AppRoutes.groupSettings: (context) {
          final args = ModalRoute.of(context)?.settings.arguments
              as Map<String, dynamic>?;
          return GroupSettingsScreen(
            groupId: args?['groupId']?.toString() ?? '',
          );
        },
        AppRoutes.groupProfile: (context) {
          final args = ModalRoute.of(context)?.settings.arguments
              as Map<String, dynamic>?;
          return GroupSettingsScreen(
            groupId: args?['groupId']?.toString() ?? '',
            isProfileMode: true, // Set to profile mode
          );
        },
        AppRoutes.moodTracking: (_) => const MoodTrackingScreen(),
        AppRoutes.qrCode: (_) => const QRCodeScreen(),
        AppRoutes.qrScanner: (_) => const QRScannerScreen(),
        AppRoutes.profile: (context) {
          final args = ModalRoute.of(context)?.settings.arguments
              as Map<String, dynamic>?;
          return ProfileScreen(userId: args?['userId']?.toString());
        },
        AppRoutes.editProfile: (_) => const EditProfileScreen(),
        AppRoutes.settings: (_) => const SettingsScreen(),
        AppRoutes.privacySettings: (_) => const PrivacySettingsScreen(),
        AppRoutes.unblockRequests: (_) => const UnblockRequestsScreen(),
      },
    );
  }
}
